const mongoose = require("mongoose");

const casoSchema = mongoose.Schema({
    sector: {type:String,  required: true},
    otracon: {type:String},
    irritabi: {type:String},
    rectrata: {type:String},
    ocupacio: {type:String,  required: true},
    inmusupr: {type:String},
    cventine: {type:Number},
    hiperten: {type:String},
    rango_de_edad: {type:Number},
    artral: {type:String},
    labora: {type:String,  required: true},
    enfcardi: {type:String},
    fecingre: {type:Number},
    evoluci: {type:String},
    ataedoge: {type:String},
    vih_sida: {type:String},
    conanima: {type:String},
    conjun: {type:String},
    disnea: {type:String},
    vacunado: {type:String,  required: true},
    tos: {type:String},
    insrencr: {type:String},
    asma: {type:String},
    cvemuni:{type:Number},
    txantivi: {type:String},
    inisubis: {type:String},
    epoc: {type:String},
    cveentuni: {type:Number},
    hableind: {type:String},
    odinogia: {type:String},
    tipacien: {type:String},
    origen: {type:String},
    seringre: {type:String},
    conocaso: {type:String},
    contaves: {type:String},
    entidad: {type:String,  required: true},
    edad: {type:Number,  required: true},
    cianosis: {type:String},
    txcrobia: {type:String},
    locresi: {type:String,  required: true},
    diabetes: {type:String},
    fecinisi: {type:Number},
    dotoraci: {type:String},
    esindige: {type:String},
    antipireticos: {type:String},
    sexo: {type:String,  required: true},
    tommue: {type:String},
    delega: {type:String},
    fechreg: {type:Date,  required: true},
    mpioresi: {type:String,  required: true},
    mialgias: {type:String},
    entresi: {type:String,  required: true},
    cvelocal: {type:Number},
    vomito: {type:String},
    dolabdo: {type:String},
    naciona: {type:String,  required: true},
    unidad: {type:String,  required: true},
    rinorrea: {type:String},
    polipnea: {type:String},
    tabaquis: {type:String},
    diarrea: {type:String},
    cefalea: {type:String},
    digcline: {type:String},
    resdefin: {type:String,  required: true},
    calofrios: {type:String},
    concerdo: {type:String},
    obesidad: {type:String},
    diagprob:{type:String},
    fiebre: {type:String}
});

module.exports = mongoose.model("Caso", casoSchema);